version: '3'
services:
  docker-centos-vnc:
    privileged: true
    tty: true
    image: terwer/centos:7
    container_name: docker-centos
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 5901:5901
      - 3000:3000
      - 3001:3001
      - 8080:8080
      - 8081:8081
      - 8090:8090
      - 8091:8091
      - 9090:9090
    volumes:
      - ./share:/share
      - ./sys/fs/cgroup:/sys/fs/cgroup:ro