# docker-compose --log-level INFO up --build docker-centos-vnc
# docker-compose --log-level INFO up

version: '3'
services:
  centos-7-vnc:
    image: terwer/centos7:7
    container_name: centos-7-vnc
    build:
      context: ./centos-7-vnc
      dockerfile: Dockerfile
    ports:
      - "5901:5901"
      - "3000:3000"
      - "3001:3001"
      - "8080:8080"
      - "8081:8081"
      - "8090:8090"
      - "8091:8091"
      - "9090:9090"
    volumes:
      - ./centos-7-vnc/mytemp:/mytemp
      - ./centos-7-vnc/config:/config
      - ./centos-7-vnc/env:/env
      - ./centos-7-vnc/app:/app
      - ./centos-7-vnc/scripts:/scripts
      - ./centos-7-vnc/workspace:/workspace
    privileged: true
    tty: true
    stdin_open: true