# 每次修改配置需要重新打包镜像并重建
# !!! 注意，此操作会删除所有的手动改动数据
# docker-compose --log-level INFO up -d --build --force-recreate docker-centos-vnc
# 一般修改脚本只需要用下面的
# docker-compose --log-level INFO up -d --build docker-centos-vnc
# 常规启动
# docker-compose --log-level INFO up -d

# FOR DEV ONLY
# docker-compose --log-level INFO up --build --force-recreate docker-centos-vnc
# docker-compose --log-level INFO up --build docker-centos-vnc
# docker-compose --log-level INFO up

version: '3'
services:
  docker-centos-vnc:
    privileged: true
    tty: true
    image: terwer/centos:7
    container_name: docker-centos
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 5901:5901
      - 3000:3000
      - 3001:3001
      - 8080:8080
      - 8081:8081
      - 8090:8090
      - 8091:8091
      - 9090:9090
    volumes:
      - ./home:/home
      - ./app:/app
      - ./env:/env
      - ./share:/share
